### PR TITLE
idle sweeper: Don't close connections with pending calls

### LINKED ISSUE #701: Calls can still be pending for a connection that's idle
If the idle checker has kicked for any particular connection and there're still calls inflight, then something else is going wrong.

* Place some logging to identify that this has happened.
* Don't try to close the connection if there is a pending call.
* Make sure that the idle check timeout is greater than the call timeout.

### PR DESCRIPTION
**Pull request by prashantv**
As documented in #701, we currently attempt closing connections even
if they have pending calls. This can cause issues if the calls is stuck
as the connection enters start-close, so it'll reject new incoming
calls, but it doesn't close, so the remote side keeps sending calls over
the same connection.

Fixes #701.

### CODE REVIEW

File: idle_sweep_test.go [hunk 1]
```diff
@@ -280,3 +282,64 @@ func TestIdleSweepMisconfiguration(t *testing.T) {
...
+func TestIdleSweepIgnoresConnectionsWithCalls(t *testing.T) {
+	ctx, cancel := NewContext(time.Second)
+	defer cancel()
+
+	clientTicker := testutils.NewFakeTicker()
+	clock := testutils.NewStubClock(time.Now())
+
+	listener := newPeerStatusListener()
+	serverOpts := testutils.NewOpts().
+		AddLogFilter("Skip closing idle Connection as it has pending calls.", 1).
```
Comment (witriew) [inline idle_sweep_test.go]: Was looking over this and I initially thought that it would check and verify for this log message. It'd probably be great if we could do that as well.

Comment (prashantv) [reply idle_sweep_test.go]: Added a TODO
