### PR TITLE
relay: Ensure idle sweeper also considers relay calls

### LINKED ISSUE #701: Calls can still be pending for a connection that's idle
If the idle checker has kicked for any particular connection and there're still calls inflight, then something else is going wrong.

* Place some logging to identify that this has happened.
* Don't try to close the connection if there is a pending call.
* Make sure that the idle check timeout is greater than the call timeout.

### PR DESCRIPTION
**Pull request by prashantv**
The previous fix for #701 avoids the idle sweeper from closing
connections with pending calls. However, it didn't take into account
relay calls (which do not set up exchanges). Ensure we take any pending
relay calls into account as well.

Fixes #701 for pending calls on relays as well as clients/servers.

### CODE REVIEW

File: idle_sweep_test.go [hunk 1]
```diff
@@ -326,21 +326,48 @@ func TestIdleSweepIgnoresConnectionsWithCalls(t *testing.T) {
...
+			preCloseConns int
+			tick          func()
+		}{
+			ch:            ts.Server(),
+			preCloseConns: 2,
+			tick: func() {
+				clock.Elapse(5 * time.Minute)
+				clientTicker.Tick()
+			},
+		}
```
Comment (witriew) [inline idle_sweep_test.go]: nit: newline
