### PR TITLE
relay: Fix race between connection close and new call

### LINKED ISSUE #370: Relay: race between items being added and the connection closing
To avoid races between relay items and connection state changes, we need to atomically increment pending and check the connection state. Similarly, the connection close checks needs to check the pending count atomically and change the state to closed.

### PR DESCRIPTION
**Pull request by prashantv**
Currently, relay items are added without checking the connection state.
This can lead to new items being added while a connection is closing.

This change makes checking the connection state atomic with incrementing
the pending count. This ensures that only active connections can accept
new incoming calls.

Fixes #370

### CODE REVIEW

File: relay.go [hunk 1]
```diff
@@ -214,7 +214,30 @@ func (r *Relayer) Receive(f *Frame, fType frameType) {
 	}
 }
 
+func (r *Relayer) canHandleNewCall(outbound bool) bool {
+
```
Comment (abhinav) [inline relay.go]: nit: delete empty line

File: relay_test.go [hunk 2]
```diff
@@ -6,11 +6,14 @@ import (
 	"testing"
 	"time"
 
-	"github.com/stretchr/testify/assert"
-	"github.com/stretchr/testify/require"
 	. "github.com/uber/tchannel-go"
+
+	"github.com/uber/tchannel-go/atomic"
```
Comment (breerly) [inline relay_test.go]: How generic is this package? Perhaps move to uber-go?

File: relay_test.go [hunk 3]
```diff
@@ -160,3 +163,46 @@ func TestErrorFrameEndsRelay(t *testing.T) {
 		assert.Equal(t, ErrCodeBadRequest, se.Code(), "Expected BadRequest error")
 	})
 }
+
+// Trigger a race between receiving a new call and a connection closing
+// by closing the relay while a lot of background calls are being made.
+func TestRaceCloseWithNewCall(t *testing.T) {
```
Comment (breerly) [inline relay_test.go]: How does this test behave with the implementation backed out? Hangs forever?

File: relay_test.go (hunk 2 above)
Comment (prashantv) [inline relay_test.go]: already in progress!
https://github.com/uber-go/atomic/pull/1

File: relay_test.go (hunk 3 above)
Comment (prashantv) [inline relay_test.go]: Sometimes causes races, sometimes panics.

Comment (prashantv) [inline relay_test.go]: Added more clients making concurrent calls so now it always panics without this change.

**Comment by akshayjshah** [comment]
lgtm.
