### PR TITLE
Clone headers when injecting tracing data for outbound request

### LINKED ISSUE #505: Concurrent calls using the same context with headers could lead to a panic
The thrift client calls `InjectOutboundSpan` with the headers passed in to the context,
https://github.com/uber/tchannel-go/blob/dev/thrift/client.go#L69

This method will modify the passed in map (if it's not nil):
https://github.com/uber/tchannel-go/blob/dev/tracing.go#L178

If there's concurrent calls using the same context with the same map, they will both try to modify the map (causing a data race) which since go1.7 may also trigger the following panic:
```
fatal error: concurrent map writes
```

@yurishkuro

### PR DESCRIPTION
**Pull request by yurishkuro**
Fixes #505

### CODE REVIEW

File: tracing.go [hunk 1]
```diff
@@ -166,21 +166,28 @@ func (c *Connection) startOutboundSpan(ctx context.Context, serviceName, methodN
...
-	carrier := tracingHeadersCarrier(headers)
+	newHeaders := make(map[string]string)
+	carrier := tracingHeadersCarrier(newHeaders)
 	if err := span.Tracer().Inject(span.Context(), opentracing.TextMap, carrier); err != nil {
 		// Something had to go seriously wrong for Inject to fail, usually a setup problem.
 		// A good Tracer implementation may also emit a metric.
 		response.log.WithFields(ErrField(err)).Error("Failed to inject tracing span.")
 	}
-	return headers
+	if len(newHeaders) == 0 {
```
Comment (junchaowu) [inline tracing.go]: here is len(newHeaders) == 0 or len(headers) == 0 ?

Comment (yurishkuro) [inline tracing.go]: newHeaders - it's checking that tracer did not include any keys, thus the original map can be returned

**Comment by prashantv** [comment]
Can we add a test that triggers a data race without the fix, that should be fixed by this change?

**Comment by yurishkuro** [comment]
@prashantv is it ok to use `import "golang.org/x/sync/errgroup"`?

**Comment by prashantv** [comment]
@yurishkuro we can but I don't think we need it, since we are in a test context and can `assert.NoError`
```go

ctx, cancel := // create context with a single headers map
defer cancel() 

var sync.WaitGroup
for i := 0; i < 5; i++ {
  wg.Add(1)
  go func() {
    defer wg.Done()
    for i := 0; i < 10; i++ {
      json.Call(ctx, ....)
    }
  }
}
wg.Wait()
```

That should be enough to trigger the race right?

File: tracing.go [hunk 2]
```diff
@@ -166,21 +166,28 @@ func (c *Connection) startOutboundSpan(ctx context.Context, serviceName, methodN
...
 	if span == nil {
 		return headers
 	}
-	if headers == nil {
-		headers = make(map[string]string)
-	}
-	carrier := tracingHeadersCarrier(headers)
+	newHeaders := make(map[string]string)
+	carrier := tracingHeadersCarrier(newHeaders)
 	if err := span.Tracer().Inject(span.Context(), opentracing.TextMap, carrier); err != nil {
```
Comment (eculver) [inline tracing.go]: It's hard to see what's actually going on here because the `carrier` is actually the one operating on the headers map. It seems more reasonable for the tracer to always make a new headers map on `Inject` rather than try to understand all the implicit mutations that are going on. It's probably outside the scope of this PR, but I think it should be the responsibility of `Tracer().Inject()` to create the new map if it's going to make these assumptions.

Comment (yurishkuro) [inline tracing.go]: the point of Inject() is to affect the outgoing request's headers

File: tracing_test.go [hunk 3]
```diff
@@ -138,3 +139,43 @@ func TestTracingSpanAttributes(t *testing.T) {
...
+
+// Per https://github.com/uber/tchannel-go/issues/505, concurrent client calls
+// made with the same shared map used as headers were causing panic due to
+// concurrent writes to the map when injecting tracing headers.
+func TestReusableHeaders(t *testing.T) {
+	tracer := mocktracer.New()
+
+	opts := &testutils.ChannelOpts{
+		ChannelOptions: ChannelOptions{Tracer: tracer},
+		DisableRelay:   true,
```
Comment (prashantv) [inline tracing_test.go]: do you need to disable the relay here?

**Comment by yurishkuro** [comment]
@prashantv I did reproduce the panic, but thought doing `require.NoError` inside go-routines is not a good practice. Anyway, I've added the test.

File: tracing_test.go [hunk 4]
```diff
@@ -138,3 +139,43 @@ func TestTracingSpanAttributes(t *testing.T) {
...
+
+		peer := ch.Peers().GetOrAdd(ch.PeerInfo().HostPort)
+		sharedHeaders := map[string]string{"life": "42"}
+
+		var wg sync.WaitGroup
+		for i := 0; i < 42; i++ {
+			wg.Add(1)
+			go func() {
+				defer wg.Done()
+				jsonCtx := json.WithHeaders(ctx, sharedHeaders)
```
Comment (prashantv) [inline tracing_test.go]: we should be able to create the context once at the top, i'd suggest
```go
ctx, cancel := NewContextBuilder(2 * time.Second).SetHeaders(sharedHeaders).Build()
```

File: tracing_test.go [hunk 5]
```diff
@@ -138,3 +139,43 @@ func TestTracingSpanAttributes(t *testing.T) {
...
+	opts := &testutils.ChannelOpts{
+		ChannelOptions: ChannelOptions{Tracer: tracer},
+		DisableRelay:   true,
+	}
+	WithVerifiedServer(t, opts, func(ch *Channel, hostPort string) {
+		jsonHandler := &JSONHandler{TraceHandler: testtracing.TraceHandler{Ch: ch}, t: t}
+		json.Register(ch, json.Handlers{"call": jsonHandler.callJSON}, jsonHandler.onError)
+
+		span := ch.Tracer().StartSpan("client")
+		ctx := opentracing.ContextWithSpan(context.Background(), span)
```
Comment (prashantv) [inline tracing_test.go]: do we need to create a span, is that relevant to this test

File: tracing_test.go [hunk 6]
```diff
@@ -138,3 +139,43 @@ func TestTracingSpanAttributes(t *testing.T) {
...
+
+		var wg sync.WaitGroup
+		for i := 0; i < 42; i++ {
+			wg.Add(1)
+			go func() {
+				defer wg.Done()
+				jsonCtx := json.WithHeaders(ctx, sharedHeaders)
+				var response testtracing.TracingResponse
+				require.NoError(t,
+					json.CallPeer(jsonCtx, peer, ch.PeerInfo().ServiceName,
```
Comment (prashantv) [inline tracing_test.go]: i think you can do `ch.ServiceName()` instead

File: tracing_test.go [hunk 7]
```diff
@@ -138,3 +139,43 @@ func TestTracingSpanAttributes(t *testing.T) {
...
+						"call", &testtracing.TracingRequest{}, &response))
```
Comment (prashantv) [inline tracing_test.go]: can we add a message saying that "json.Call failed"

File: tracing_test.go [hunk 8]
```diff
@@ -138,3 +139,43 @@ func TestTracingSpanAttributes(t *testing.T) {
...
 }
+
+// Per https://github.com/uber/tchannel-go/issues/505, concurrent client calls
+// made with the same shared map used as headers were causing panic due to
+// concurrent writes to the map when injecting tracing headers.
+func TestReusableHeaders(t *testing.T) {
+	tracer := mocktracer.New()
+
+	opts := &testutils.ChannelOpts{
+		ChannelOptions: ChannelOptions{Tracer: tracer},
```
Comment (prashantv) [inline tracing_test.go]: can we inline the `mocktracer.New` in here?

**Comment by prashantv** [comment]
`require.NoError` inside of a goroutine is a bad idea, but `assert.NoError` is fine, so let's switch to that.

File: tracing_test.go (hunk 5 above)
Comment (yurishkuro) [inline tracing_test.go]: I'll add validation, otherwise we don't know if tracing is even propagated / headers being modified

File: tracing.go (hunk 1 above)
Comment (yurishkuro) [inline tracing.go]: added comment

**Comment by prashantv** [comment]
lgtm, thanks for the quick fix @yurishkuro
