### PR TITLE
Only create Connection object for active TChannel connections

### LINKED ISSUE #584: Data races on setting remote peer info
We update the `log` object with extra information about peers during the init handshake. During the init handshake, there's no calls, but there's a few cases that can trigger a read of `c.log` while the init handshake sets `c.log`:
 - connection errors
 - calls to `connection.Close`

See data races in this Travis run:
https://travis-ci.org/uber/tchannel-go/jobs/201305663

We have a few options:
1. don't set `c.log` after the connection is created (but then we lose extra information in the log object that's very useful for debugging)
2. don't create a connection object until the init handshake is done
3. use locks around `c.log` in the specific cases that we know can race during init.

(2) is the correct solution but requires a lot of refactoring. (3) is a short-term fix but we'll need to be careful about ensuring there's locks everywhere needed without affecting performance.

```
==================
==================
WARNING: DATA RACE
Write by goroutine 273:
  github.com/uber/tchannel-go.(*Connection).parseRemotePeerAddress()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:1143 +0x560
  github.com/uber/tchannel-go.(*Connection).parseRemotePeer()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:1127 +0x534
  github.com/uber/tchannel-go.(*Connection).handleInitRes()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:604 +0x5bb
  github.com/uber/tchannel-go.(*Connection).handleFrameNoRelay()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:913 +0x14c
  github.com/uber/tchannel-go.(*Connection).readFrames()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:857 +0x46d
Previous read by goroutine 280:
  github.com/uber/tchannel-go.(*Connection).closeNetwork()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:1102 +0x5f
  github.com/uber/tchannel-go.(*Connection).writeFrames()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:965 +0x5af
Goroutine 273 (running) created at:
  github.com/uber/tchannel-go.(*Channel).newConnection()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:303 +0x1157
  github.com/uber/tchannel-go.(*Channel).newOutboundConnection()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:253 +0xac1
  github.com/uber/tchannel-go.(*Channel).Connect()
      github.com/uber/tchannel-go/_test/_obj_test/channel.go:494 +0x4a4
  github.com/uber/tchannel-go.(*Peer).Connect()
      github.com/uber/tchannel-go/_test/_obj_test/peer.go:555 +0xd1
  github.com/uber/tchannel-go.(*Peer).GetConnection()
      github.com/uber/tchannel-go/_test/_obj_test/peer.go:423 +0x1ea
  github.com/uber/tchannel-go.(*Channel).Ping()
      github.com/uber/tchannel-go/_test/_obj_test/channel.go:425 +0xaa
  github.com/uber/tchannel-go_test.TestRaceExchangesWithClose.func1.4()
      /home/travis/gopath/src/github.com/uber/tchannel-go/close_test.go:150 +0x145
Goroutine 280 (finished) created at:
  github.com/uber/tchannel-go.(*Channel).newConnection()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:304 +0x1181
  github.com/uber/tchannel-go.(*Channel).newOutboundConnection()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:253 +0xac1
  github.com/uber/tchannel-go.(*Channel).Connect()
      github.com/uber/tchannel-go/_test/_obj_test/channel.go:494 +0x4a4
  github.com/uber/tchannel-go.(*Peer).Connect()
      github.com/uber/tchannel-go/_test/_obj_test/peer.go:555 +0xd1
  github.com/uber/tchannel-go.(*Peer).GetConnection()
      github.com/uber/tchannel-go/_test/_obj_test/peer.go:423 +0x1ea
  github.com/uber/tchannel-go.(*Channel).Ping()
      github.com/uber/tchannel-go/_test/_obj_test/channel.go:425 +0xaa
  github.com/uber/tchannel-go_test.TestRaceExchangesWithClose.func1.4()
      /home/travis/gopath/src/github.com/uber/tchannel-go/close_test.go:150 +0x145
==================
==================
WARNING: DATA RACE
Write by goroutine 262:
  github.com/uber/tchannel-go.(*Connection).parseRemotePeer()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:1116 +0xd1
  github.com/uber/tchannel-go.(*Connection).handleInitRes()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:604 +0x5bb
  github.com/uber/tchannel-go.(*Connection).handleFrameNoRelay()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:913 +0x14c
  github.com/uber/tchannel-go.(*Connection).readFrames()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:857 +0x46d
Previous read by goroutine 173:
  ??()
      -:0 +0xffffffffffffffff
  github.com/uber/tchannel-go.(*messageExchangeSet).stopExchanges()
      github.com/uber/tchannel-go/_test/_obj_test/mex.go:567 +0x2bb
  github.com/uber/tchannel-go.(*Connection).connectionError()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:784 +0x1b5
  github.com/uber/tchannel-go.(*Connection).sendInit()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:427 +0x927
  github.com/uber/tchannel-go.(*Channel).Connect()
      github.com/uber/tchannel-go/_test/_obj_test/channel.go:501 +0x573
  github.com/uber/tchannel-go.(*Peer).Connect()
      github.com/uber/tchannel-go/_test/_obj_test/peer.go:555 +0xd1
  github.com/uber/tchannel-go.(*Peer).GetConnection()
      github.com/uber/tchannel-go/_test/_obj_test/peer.go:423 +0x1ea
  github.com/uber/tchannel-go.(*Channel).Ping()
      github.com/uber/tchannel-go/_test/_obj_test/channel.go:425 +0xaa
  github.com/uber/tchannel-go_test.TestRaceExchangesWithClose.func1.4()
      /home/travis/gopath/src/github.com/uber/tchannel-go/close_test.go:150 +0x145
Goroutine 262 (running) created at:
  github.com/uber/tchannel-go.(*Channel).newConnection()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:303 +0x1157
  github.com/uber/tchannel-go.(*Channel).newOutboundConnection()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:253 +0xac1
  github.com/uber/tchannel-go.(*Channel).Connect()
      github.com/uber/tchannel-go/_test/_obj_test/channel.go:494 +0x4a4
  github.com/uber/tchannel-go.(*Peer).Connect()
      github.com/uber/tchannel-go/_test/_obj_test/peer.go:555 +0xd1
  github.com/uber/tchannel-go.(*Peer).GetConnection()
      github.com/uber/tchannel-go/_test/_obj_test/peer.go:423 +0x1ea
  github.com/uber/tchannel-go.(*Channel).Ping()
      github.com/uber/tchannel-go/_test/_obj_test/channel.go:425 +0xaa
  github.com/uber/tchannel-go_test.TestRaceExchangesWithClose.func1.4()
      /home/travis/gopath/src/github.com/uber/tchannel-go/close_test.go:150 +0x145
Goroutine 173 (finished) created at:
  github.com/uber/tchannel-go_test.TestRaceExchangesWithClose.func1()
      /home/travis/gopath/src/github.com/uber/tchannel-go/close_test.go:152 +0x45f
  github.com/uber/tchannel-go/testutils.withServer()
      /home/travis/gopath/src/github.com/uber/tchannel-go/testutils/test_server.go:445 +0x8f
  github.com/uber/tchannel-go/testutils.WithTestServer()
      /home/travis/gopath/src/github.com/uber/tchannel-go/testutils/test_server.go:121 +0x2b5
  github.com/uber/tchannel-go_test.TestRaceExchangesWithClose()
      /home/travis/gopath/src/github.com/uber/tchannel-go/close_test.go:161 +0x239
  testing.tRunner()
      /home/travis/.gimme/versions/go1.6.linux.amd64/src/testing/testing.go:473 +0xdc
==================
==================
WARNING: DATA RACE
Write by goroutine 262:
  github.com/uber/tchannel-go.(*Connection).parseRemotePeerAddress()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:1143 +0x560
  github.com/uber/tchannel-go.(*Connection).parseRemotePeer()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:1127 +0x534
  github.com/uber/tchannel-go.(*Connection).handleInitRes()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:604 +0x5bb
  github.com/uber/tchannel-go.(*Connection).handleFrameNoRelay()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:913 +0x14c
  github.com/uber/tchannel-go.(*Connection).readFrames()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:857 +0x46d
Previous read by goroutine 173:
  ??()
      -:0 +0xffffffffffffffff
  github.com/uber/tchannel-go.(*messageExchangeSet).stopExchanges()
      github.com/uber/tchannel-go/_test/_obj_test/mex.go:567 +0x2bb
  github.com/uber/tchannel-go.(*Connection).connectionError()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:784 +0x1b5
  github.com/uber/tchannel-go.(*Connection).sendInit()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:427 +0x927
  github.com/uber/tchannel-go.(*Channel).Connect()
      github.com/uber/tchannel-go/_test/_obj_test/channel.go:501 +0x573
  github.com/uber/tchannel-go.(*Peer).Connect()
      github.com/uber/tchannel-go/_test/_obj_test/peer.go:555 +0xd1
  github.com/uber/tchannel-go.(*Peer).GetConnection()
      github.com/uber/tchannel-go/_test/_obj_test/peer.go:423 +0x1ea
  github.com/uber/tchannel-go.(*Channel).Ping()
      github.com/uber/tchannel-go/_test/_obj_test/channel.go:425 +0xaa
  github.com/uber/tchannel-go_test.TestRaceExchangesWithClose.func1.4()
      /home/travis/gopath/src/github.com/uber/tchannel-go/close_test.go:150 +0x145
Goroutine 262 (running) created at:
  github.com/uber/tchannel-go.(*Channel).newConnection()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:303 +0x1157
  github.com/uber/tchannel-go.(*Channel).newOutboundConnection()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:253 +0xac1
  github.com/uber/tchannel-go.(*Channel).Connect()
      github.com/uber/tchannel-go/_test/_obj_test/channel.go:494 +0x4a4
  github.com/uber/tchannel-go.(*Peer).Connect()
      github.com/uber/tchannel-go/_test/_obj_test/peer.go:555 +0xd1
  github.com/uber/tchannel-go.(*Peer).GetConnection()
      github.com/uber/tchannel-go/_test/_obj_test/peer.go:423 +0x1ea
  github.com/uber/tchannel-go.(*Channel).Ping()
      github.com/uber/tchannel-go/_test/_obj_test/channel.go:425 +0xaa
  github.com/uber/tchannel-go_test.TestRaceExchangesWithClose.func1.4()
      /home/travis/gopath/src/github.com/uber/tchannel-go/close_test.go:150 +0x145
Goroutine 173 (finished) created at:
  github.com/uber/tchannel-go_test.TestRaceExchangesWithClose.func1()
      /home/travis/gopath/src/github.com/uber/tchannel-go/close_test.go:152 +0x45f
  github.com/uber/tchannel-go/testutils.withServer()
      /home/travis/gopath/src/github.com/uber/tchannel-go/testutils/test_server.go:445 +0x8f
  github.com/uber/tchannel-go/testutils.WithTestServer()
      /home/travis/gopath/src/github.com/uber/tchannel-go/testutils/test_server.go:121 +0x2b5
  github.com/uber/tchannel-go_test.TestRaceExchangesWithClose()
      /home/travis/gopath/src/github.com/uber/tchannel-go/close_test.go:161 +0x239
  testing.tRunner()
      /home/travis/.gimme/versions/go1.6.linux.amd64/src/testing/testing.go:473 +0xdc
==================
==================
WARNING: DATA RACE
Write by goroutine 178:
  github.com/uber/tchannel-go.(*Connection).parseRemotePeer()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:1116 +0xd1
  github.com/uber/tchannel-go.(*Connection).handleInitRes()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:604 +0x5bb
  github.com/uber/tchannel-go.(*Connection).handleFrameNoRelay()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:913 +0x14c
  github.com/uber/tchannel-go.(*Connection).readFrames()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:857 +0x46d
Previous read by goroutine 75:
  ??()
      -:0 +0xffffffffffffffff
  sync.(*RWMutex).Lock()
      /home/travis/.gimme/versions/go1.6.linux.amd64/src/sync/rwmutex.go:91 +0xcb
  github.com/uber/tchannel-go.(*messageExchangeSet).stopExchanges()
      github.com/uber/tchannel-go/_test/_obj_test/mex.go:566 +0x2aa
  github.com/uber/tchannel-go.(*Connection).connectionError()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:784 +0x1b5
  github.com/uber/tchannel-go.(*Connection).sendInit()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:427 +0x927
  github.com/uber/tchannel-go.(*Channel).Connect()
      github.com/uber/tchannel-go/_test/_obj_test/channel.go:501 +0x573
  github.com/uber/tchannel-go.(*Peer).Connect()
      github.com/uber/tchannel-go/_test/_obj_test/peer.go:555 +0xd1
  github.com/uber/tchannel-go.(*Peer).GetConnection()
      github.com/uber/tchannel-go/_test/_obj_test/peer.go:423 +0x1ea
  github.com/uber/tchannel-go.(*Channel).Ping()
      github.com/uber/tchannel-go/_test/_obj_test/channel.go:425 +0xaa
  github.com/uber/tchannel-go_test.TestRaceExchangesWithClose.func1.4()
      /home/travis/gopath/src/github.com/uber/tchannel-go/close_test.go:150 +0x145
Goroutine 178 (running) created at:
  github.com/uber/tchannel-go.(*Channel).newConnection()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:303 +0x1157
  github.com/uber/tchannel-go.(*Channel).newOutboundConnection()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:253 +0xac1
  github.com/uber/tchannel-go.(*Channel).Connect()
      github.com/uber/tchannel-go/_test/_obj_test/channel.go:494 +0x4a4
  github.com/uber/tchannel-go.(*Peer).Connect()
      github.com/uber/tchannel-go/_test/_obj_test/peer.go:555 +0xd1
  github.com/uber/tchannel-go.(*Peer).GetConnection()
      github.com/uber/tchannel-go/_test/_obj_test/peer.go:423 +0x1ea
  github.com/uber/tchannel-go.(*Channel).Ping()
      github.com/uber/tchannel-go/_test/_obj_test/channel.go:425 +0xaa
  github.com/uber/tchannel-go_test.TestRaceExchangesWithClose.func1.4()
      /home/travis/gopath/src/github.com/uber/tchannel-go/close_test.go:150 +0x145
Goroutine 75 (finished) created at:
  github.com/uber/tchannel-go_test.TestRaceExchangesWithClose.func1()
      /home/travis/gopath/src/github.com/uber/tchannel-go/close_test.go:152 +0x45f
  github.com/uber/tchannel-go/testutils.withServer()
      /home/travis/gopath/src/github.com/uber/tchannel-go/testutils/test_server.go:445 +0x8f
  github.com/uber/tchannel-go/testutils.WithTestServer()
      /home/travis/gopath/src/github.com/uber/tchannel-go/testutils/test_server.go:121 +0x2b5
  github.com/uber/tchannel-go_test.TestRaceExchangesWithClose()
      /home/travis/gopath/src/github.com/uber/tchannel-go/close_test.go:161 +0x239
  testing.tRunner()
      /home/travis/.gimme/versions/go1.6.linux.amd64/src/testing/testing.go:473 +0xdc
==================
==================
WARNING: DATA RACE
Write by goroutine 178:
  github.com/uber/tchannel-go.(*Connection).parseRemotePeerAddress()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:1143 +0x560
  github.com/uber/tchannel-go.(*Connection).parseRemotePeer()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:1127 +0x534
  github.com/uber/tchannel-go.(*Connection).handleInitRes()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:604 +0x5bb
  github.com/uber/tchannel-go.(*Connection).handleFrameNoRelay()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:913 +0x14c
  github.com/uber/tchannel-go.(*Connection).readFrames()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:857 +0x46d
Previous read by goroutine 75:
  ??()
      -:0 +0xffffffffffffffff
  sync.(*RWMutex).Lock()
      /home/travis/.gimme/versions/go1.6.linux.amd64/src/sync/rwmutex.go:91 +0xcb
  github.com/uber/tchannel-go.(*messageExchangeSet).stopExchanges()
      github.com/uber/tchannel-go/_test/_obj_test/mex.go:566 +0x2aa
  github.com/uber/tchannel-go.(*Connection).connectionError()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:784 +0x1b5
  github.com/uber/tchannel-go.(*Connection).sendInit()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:427 +0x927
  github.com/uber/tchannel-go.(*Channel).Connect()
      github.com/uber/tchannel-go/_test/_obj_test/channel.go:501 +0x573
  github.com/uber/tchannel-go.(*Peer).Connect()
      github.com/uber/tchannel-go/_test/_obj_test/peer.go:555 +0xd1
  github.com/uber/tchannel-go.(*Peer).GetConnection()
      github.com/uber/tchannel-go/_test/_obj_test/peer.go:423 +0x1ea
  github.com/uber/tchannel-go.(*Channel).Ping()
      github.com/uber/tchannel-go/_test/_obj_test/channel.go:425 +0xaa
  github.com/uber/tchannel-go_test.TestRaceExchangesWithClose.func1.4()
      /home/travis/gopath/src/github.com/uber/tchannel-go/close_test.go:150 +0x145
Goroutine 178 (running) created at:
  github.com/uber/tchannel-go.(*Channel).newConnection()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:303 +0x1157
  github.com/uber/tchannel-go.(*Channel).newOutboundConnection()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:253 +0xac1
  github.com/uber/tchannel-go.(*Channel).Connect()
      github.com/uber/tchannel-go/_test/_obj_test/channel.go:494 +0x4a4
  github.com/uber/tchannel-go.(*Peer).Connect()
      github.com/uber/tchannel-go/_test/_obj_test/peer.go:555 +0xd1
  github.com/uber/tchannel-go.(*Peer).GetConnection()
      github.com/uber/tchannel-go/_test/_obj_test/peer.go:423 +0x1ea
  github.com/uber/tchannel-go.(*Channel).Ping()
      github.com/uber/tchannel-go/_test/_obj_test/channel.go:425 +0xaa
  github.com/uber/tchannel-go_test.TestRaceExchangesWithClose.func1.4()
      /home/travis/gopath/src/github.com/uber/tchannel-go/close_test.go:150 +0x145
Goroutine 75 (finished) created at:
  github.com/uber/tchannel-go_test.TestRaceExchangesWithClose.func1()
      /home/travis/gopath/src/github.com/uber/tchannel-go/close_test.go:152 +0x45f
  github.com/uber/tchannel-go/testutils.withServer()
      /home/travis/gopath/src/github.com/uber/tchannel-go/testutils/test_server.go:445 +0x8f
  github.com/uber/tchannel-go/testutils.WithTestServer()
      /home/travis/gopath/src/github.com/uber/tchannel-go/testutils/test_server.go:121 +0x2b5
  github.com/uber/tchannel-go_test.TestRaceExchangesWithClose()
      /home/travis/gopath/src/github.com/uber/tchannel-go/close_test.go:161 +0x239
  testing.tRunner()
      /home/travis/.gimme/versions/go1.6.linux.amd64/src/testing/testing.go:473 +0xdc
==================
==================
WARNING: DATA RACE
Write by goroutine 278:
  github.com/uber/tchannel-go.(*Connection).parseRemotePeerAddress()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:1143 +0x560
  github.com/uber/tchannel-go.(*Connection).parseRemotePeer()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:1127 +0x534
  github.com/uber/tchannel-go.(*Connection).handleInitRes()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:604 +0x5bb
  github.com/uber/tchannel-go.(*Connection).handleFrameNoRelay()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:913 +0x14c
  github.com/uber/tchannel-go.(*Connection).readFrames()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:857 +0x46d
Previous read by goroutine 246:
  [failed to restore the stack]
Goroutine 278 (running) created at:
  github.com/uber/tchannel-go.(*Channel).newConnection()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:303 +0x1157
  github.com/uber/tchannel-go.(*Channel).newOutboundConnection()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:253 +0xac1
  github.com/uber/tchannel-go.(*Channel).Connect()
      github.com/uber/tchannel-go/_test/_obj_test/channel.go:494 +0x4a4
  github.com/uber/tchannel-go.(*Peer).Connect()
      github.com/uber/tchannel-go/_test/_obj_test/peer.go:555 +0xd1
  github.com/uber/tchannel-go.(*Peer).GetConnection()
      github.com/uber/tchannel-go/_test/_obj_test/peer.go:423 +0x1ea
  github.com/uber/tchannel-go.(*Channel).Ping()
      github.com/uber/tchannel-go/_test/_obj_test/channel.go:425 +0xaa
  github.com/uber/tchannel-go_test.TestRaceExchangesWithClose.func1.4()
      /home/travis/gopath/src/github.com/uber/tchannel-go/close_test.go:150 +0x145
Goroutine 246 (finished) created at:
  github.com/uber/tchannel-go.(*Channel).newConnection()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:304 +0x1181
  github.com/uber/tchannel-go.(*Channel).newOutboundConnection()
      github.com/uber/tchannel-go/_test/_obj_test/connection.go:253 +0xac1
  github.com/uber/tchannel-go.(*Channel).Connect()
      github.com/uber/tchannel-go/_test/_obj_test/channel.go:494 +0x4a4
  github.com/uber/tchannel-go.(*Peer).Connect()
      github.com/uber/tchannel-go/_test/_obj_test/peer.go:555 +0xd1
  github.com/uber/tchannel-go.(*Peer).GetConnection()
      github.com/uber/tchannel-go/_test/_obj_test/peer.go:423 +0x1ea
  github.com/uber/tchannel-go.(*Channel).Ping()
      github.com/uber/tchannel-go/_test/_obj_test/channel.go:425 +0xaa
  github.com/uber/tchannel-go_test.TestRaceExchangesWithClose.func1.4()
      /home/travis/gopath/src/github.com/uber/tchannel-go/close_test.go:150 +0x145
==================
--- PASS: TestRaceExchangesWithClose (1.97s)
```

### PR DESCRIPTION
**Pull request by prashantv**
Currently, we create a Connection object as soon as we have a TCP
connection, and then we try to add more information (such as remote peer
information) to the logging context after the init handshake. This can
lead to data races since we're modifying the logging context while
other goroutines may be logging messages with the same context.

Instead of using locks for the logging context, instead separate the
handshake phase of connections out of Connection.

Fixes #584

### CODE REVIEW

File: connection.go [hunk 1]
```diff
@@ -100,19 +96,11 @@ var (
 	// on a closed connection
 	ErrConnectionClosed = errors.New("connection is closed")
 
-	// ErrConnectionNotReady is returned when a caller attempts to send a
-	// request through a connection which has not yet been initialized
-	ErrConnectionNotReady = errors.New("connection is not yet ready")
```
Comment (akshayjshah) [inline connection.go]: Removing this is technically a breaking change. Can we keep it and just document that it's now unused?

File: connection.go [hunk 2]
```diff
@@ -254,68 +234,39 @@ func (co ConnectionOptions) withDefaults() ConnectionOptions {
...
-func (ch *Channel) newConnection(conn net.Conn, outboundHP string, initialState connectionState, events connectionEvents) *Connection {
+func (ch *Channel) newConnection(conn net.Conn, outboundHP string, remotePeer PeerInfo, remotePeerAddress peerAddressComponents, events connectionEvents) *Connection {
 	opts := ch.connectionOptions.withDefaults()
 
 	connID := _nextConnID.Inc()
 	log := ch.log.WithFields(LogFields{
 		{"connID", connID},
 		{"localAddr", conn.LocalAddr()},
 		{"remoteAddr", conn.RemoteAddr()},
+		{"remoteHostPort", remotePeer.HostPort},
```
Comment (akshayjshah) [inline connection.go]: Is there a better name we can choose for this field? To me, `remoteHostPort` isn't obviously different from `remoteAddr`.

File: peer_test.go [hunk 3]
```diff
@@ -191,12 +191,12 @@ func TestPeerRemoveClosedConnection(t *testing.T) {
 
 func TestPeerConnectCancelled(t *testing.T) {
 	WithVerifiedServer(t, nil, func(ch *Channel, hostPort string) {
-		ctx, cancel := NewContext(109 * time.Millisecond)
+		ctx, cancel := NewContext(100 * time.Millisecond)
```
Comment (akshayjshah) [inline peer_test.go]: Assuming that the original 109ms timeout was a typo...

File: peer_test.go [hunk 4]
```diff
@@ -191,12 +191,12 @@ func TestPeerRemoveClosedConnection(t *testing.T) {
...
 		cancel()
 
 		_, err := ch.Connect(ctx, "10.255.255.1:1")
 		require.Error(t, err, "Connect should fail")
-		assert.EqualError(t, ErrRequestCancelled, err.Error(), "Unknown error")
+		assert.EqualError(t, err, ErrRequestCancelled.Error(), "Unexpected error")
```
Comment (akshayjshah) [inline peer_test.go]: :( I hate this package sometimes.

File: peer_test.go [hunk 5]
```diff
@@ -582,8 +582,8 @@ func TestPeerSelection(t *testing.T) {
 		s2.GetSubChannel("S1").Peers().SetStrategy(strategy)
 		s2.GetSubChannel("S1").Peers().Add(hostPort)
 		doPing(s2)
-		assert.EqualValues(t, 5, count.Load(),
-			"Expect 5 exchange updates: peer add, init mex, new conn, ping, pong")
+		assert.EqualValues(t, 4, count.Load(),
+			"Expect 5 exchange updates: peer add, new conn, ping, pong")
```
Comment (akshayjshah) [inline peer_test.go]: nit: Update error message to 4.

File: preinit_connection.go [hunk 6]
```diff
@@ -0,0 +1,245 @@
...
+		msg.initParams[InitParamHostPort] = ephemeralHostPort
+	}
+
+	return msg
+}
+
+func (ch *Channel) initError(c net.Conn, connDir connectionDirection, id uint32, err error) error {
+	ch.log.WithFields(
+		LogField{"connectionDirection", connDir},
+		LogField{"error", err.Error()},
```
Comment (akshayjshah) [inline preinit_connection.go]: `ErrField`?

File: preinit_connection.go [hunk 7]
```diff
@@ -0,0 +1,245 @@
...
+		remotePeerAddress.hostname = address
+	}
+
+	return remotePeer, remotePeerAddress, nil
+}
+
+func setInitDeadline(ctx context.Context, c net.Conn) func() {
+	deadline, ok := ctx.Deadline()
+	if !ok {
+		deadline = time.Now().Add(5 * time.Second)
```
Comment (akshayjshah) [inline preinit_connection.go]: This seems like a very, very long time...

File: preinit_connection.go [hunk 8]
```diff
@@ -0,0 +1,245 @@
...
+	}
+
+	c.SetDeadline(deadline)
```
Comment (akshayjshah) [inline preinit_connection.go]: Do we always need to do this, or only if we're in the `!ok` block?

File: connection.go (hunk 1 above)
Comment (prashantv) [inline connection.go]: Yep, good point.

File: connection.go (hunk 2 above)
Comment (prashantv) [inline connection.go]: we could come up with a different name, but this is just a refactoring change, and this was the name of the field previously, so I'd like to avoid any renamings:
https://github.com/uber/tchannel-go/blob/dev/connection.go#L1034

File: peer_test.go (hunk 3 above)
Comment (prashantv) [inline peer_test.go]: That's what I'm assuming too, I'm pretty sure the test didn't need that extra 9ms!

File: peer_test.go (hunk 4 above)
Comment (prashantv) [inline peer_test.go]: yep, consistency is too hard :(

File: peer_test.go (hunk 5 above)
Comment (prashantv) [inline peer_test.go]: 👍

File: preinit_connection.go (hunk 6 above)
Comment (prashantv) [inline preinit_connection.go]: Totally forgot that existed, thanks!

File: preinit_connection.go (hunk 7 above)
Comment (prashantv) [inline preinit_connection.go]: Yeah :( Unfortunately tests start failing with 1 second, and I think the previous code didn't even have a timeout

File: preinit_connection.go (hunk 8 above)
Comment (prashantv) [inline preinit_connection.go]: If we have a deadline in the context, we use that, otherwise we use 5 seconds as a default timeout for inits.

We always want to set a deadline on the connection though to avoid connection exchanges that never end

Comment (akshayjshah) [inline preinit_connection.go]: My bad - I mixed up the context and the connection.

**Comment by alxn** [comment]
👍
